### ISSUE TITLE
Few small things

### ISSUE THREAD

**Issue by kylebutts** [robertsweeneyblanco/Programming_for_Mathematical_Applications#6]
Hi, I came across this on my github feed and was reading through this. This is a really nice book, y'all! 

Typos/bugs: 
- 9.2.1 has a typo `# OK, since T is 3-by-3`. It is now 5-by-5
- 9.3.1 returns false since B is an Int64 instead of a Float64 matrix

Thoughts (if I may):
- I didn't see the use of `≈` anywhere in the book which I think is super helpful for dealing with floating point math. Might fit in 7.2 or 18?

**Comment by popersson** [comment]
Thank you so much for these suggestions, they are now fixed and incorporated in time for the floating point lectures! Commit 5442075
